env:
  MIX_ENV: "test"
jobs:
  install-dependencies:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - id: "setup-beam"
        uses: "erlef/setup-beam@v1"
        with:
          elixir-version: "1.14"
          otp-version: "25.1"
      - id: "mix-cache"
        uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}"
          path: |
            deps
            _build
      - if: "steps.mix-cache.outputs.cache-hit != 'true'"
        run: |
          mix do local.hex --force, local.rebar --force, deps.get
          mix compile
  lint:
    needs: "install-dependencies"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - id: "setup-beam"
        uses: "erlef/setup-beam@v1"
        with:
          elixir-version: "1.14"
          otp-version: "25.1"
      - uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}"
          path: |
            deps
            _build
      - run: "mix deps.unlock --check-unused"
      - run: "mix credo suggest --strict"
      - run: "mix format --check-formatted"
  run-dialyzer:
    needs: "install-dependencies"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - id: "setup-beam"
        uses: "erlef/setup-beam@v1"
        with:
          elixir-version: "1.14"
          otp-version: "25.1"
      - uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}"
          path: |
            deps
            _build
      - id: "plt-cache"
        uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-plt"
          path: |
            priv/plts
      - if: "steps.plt-cache.outputs.cache-hit != 'true'"
        run: "mix dialyzer --plt"
      - run: "mix dialyzer --format github"
  test:
    env:
      PGDATABASE: "delta_check"
      PGHOST: "localhost"
      PGPASSWORD: "password"
      PGUSER: "postgres"
    needs: "install-dependencies"
    runs-on: "ubuntu-latest"
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: "postgres"
        image: "postgres:14.5-bullseye"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: "actions/checkout@v3"
      - id: "setup-beam"
        uses: "erlef/setup-beam@v1"
        with:
          elixir-version: "1.14"
          otp-version: "25.1"
      - uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}"
          path: |
            deps
            _build
      - run: "mix test"
on: ["push"]
